### ISSUE TITLE
ERROR LNK1104 The file 'SDL2.lib' could not be opened.

### ISSUE THREAD

**Issue by Tadminster** [dwjclark11/TilemapEditor#10]
Hi. Dustin Clark.

I'm trying to use the TilemapEditor you created, but I'm getting an error. Can you help me?
When I build the solution, it fails to build with the following error.

-------------------------------------------
ERROR LNK1104 The file 'SDL2.lib' could not be opened.
-------------------------------------------

Here's what I did
 
1. copy to a Git clone 
2. ran GenerateSln directly.
3. then I opened the solution file in VS2022 and built it.

 
// I attach my VS version
Microsoft Visual Studio Community 2022
version 17.6.2

**Comment by dwjclark11** [comment]
Hello, we did not have the correct SDL lib files in the path. The files should be there now. Please do a pull/download and try a new build. Let me know if that works for you.

**Comment by Tadminster** [comment]
Thanks for the answer.

I moved all the contents of the lib/x86 folder inside the ZeldaClone_NES repository to the TilemapEditor repository. 
Then it built fine.

**Comment by dwjclark11** [comment]
Awesome!! That is great. Let me know if there are any other issues. 
Thanks, I am going to close this.
